complex:
  entity_embedder:
    dropout: 0.04807801451534033
    regularize_weight: 3.380399238471697e-10
  relation_embedder:
    dropout: 0.31448999233543873
    regularize_weight: 2.0266286790449166e-06
dataset:
  name: wnrr
  num_entities: 40943
  num_relations: 11
entity_ranking:
  metrics_per:
    entity_prediction: true
    head_and_tail: true
    relation_prediction: true
    relation_type: true
  query_types:
    so_to_p: true
eval:
  batch_size: 256
import:
- complex
- reciprocal_relations_model
lookup_embedder:
  dim: 512
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.009861650776739006
    uniform_:
      a: -0.8919850567478873
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 1
    weighted: true
model: complex
modules:
- kge.model
- kge.job
- kge.model.embedder
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 0
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      args:
        lr: 0.017008336196824465
      type: Adam
  subbatch_auto_tune: true
  type: 1vsAll
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  metric: mean_reciprocal_rank_filtered_with_test_entity

