1vsAll:
  query_types:
    s_o: true
  query_weight:
    s_o: 3.815011406536214
complex:
  entity_embedder:
    dropout: -0.0061849309131503105
    regularize_weight: 8.675156461344362e-12
  relation_embedder:
    dropout: 0.39625553973019123
    regularize_weight: 2.8477450855822057e-07
dataset:
  name: wnrr
  num_entities: 40943
  num_relations: 11
entity_ranking:
  metrics_per:
    entity_prediction: true
    head_and_tail: true
    relation_prediction: true
    relation_type: true
  query_types:
    so_to_p: true
eval:
  batch_size: 256
import:
- complex
- reciprocal_relations_model
lookup_embedder:
  dim: 512
  initialize: xavier_uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.8076958433549848
    uniform_:
      a: -0.2779599902435206
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
model: complex
modules:
- kge.job
- kge.model.embedder
- kge.model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 128
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 0
    threshold: 0.0001
  max_epochs: 400
  optimizer:
    default:
      args:
        lr: 0.0028447561401542054
      type: Adam
  subbatch_auto_tune: true
  type: 1vsAll
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05

