# fb15k-complex-1vsAll-kl
job.type: search
search.type: ax
dataset.name: fb15k

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True

# this is faster for smaller datasets, but does not work for some models (e.g.,
# TransE due to a pytorch issue) or for larger datasets. Change to spo in such
# cases (either here or in ax section of model config), results will not be
# affected.
negative_sampling.implementation: sp_po

# entity ranking settings
entity_ranking:
  query_types:
    sp_to_o: True
    po_to_s: True
    so_to_p: True

# KvsAll settings
1vsAll:
  query_types:
    _po: True
    s_o: True
    sp_: True

# validation/evaluation settings (fixed)
valid:
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  filter_with_test: True
  early_stopping:
    patience: 10
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256
  metrics_per.relation_type: True
  metrics_per.head_and_tail: True
  metrics_per.relation_prediction: True
  metrics_per.entity_prediction: True

# settings for reciprocal relations (if used)
import: [complex]
# reciprocal_relations_model.base_model.type: complex
model: complex
# ax settings: hyperparameter serach space
ax_search:
  num_trials: 30
  num_sobol_trials: 30 
  parameters:
      # model
    # - name: model
    #   type: choice
    #   values: [complex, reciprocal_relations_model]

    # training hyperparameters
    - name: train.batch_size
      type: choice
      values: [128, 256, 512, 1024]
      is_ordered: True
    - name: train.type
      type: fixed
      value: 1vsAll
    - name: train.optimizer
      type: fixed
      value: Adagrad
    - name: train.loss
      type: fixed
      value: kl
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0003, 1.0]
    - name: train.lr_scheduler
      type: fixed
      value: ReduceLROnPlateau
    - name: train.lr_scheduler_args.mode
      type: fixed
      value: max  
    - name: train.lr_scheduler_args.factor
      type: fixed
      value: 0.95  
    - name: train.lr_scheduler_args.threshold
      type: fixed
      value: 0.0001  
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [0, 10]  

    # embedding dimension
    - name: lookup_embedder.dim
      type: choice 
      values: [256, 512, 1024, 2048]
      is_ordered: True

    # embedding initialization
    - name: lookup_embedder.initialize
      type: fixed
      value: normal_
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: fixed
      value: 0.001

    # embedding regularization
    - name: lookup_embedder.regularize
      type: choice
      values: ['', 'l3', 'l2', 'l1']
      is_ordered: True
    - name: lookup_embedder.regularize_args.weighted
      type: fixed
      value: True
    - name: complex.entity_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0]
    - name: complex.relation_embedder.regularize_weight
      type: range
      bounds: [1.0e-20, 1.0]

    # embedding dropout
    - name: complex.entity_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: complex.relation_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]

    # training-type specific hyperparameters
    - name: 1vsAll.query_weight.s_o
      type: range
      bounds: [0.1, 8.0]
