# fb15k-237-complex-1vsAll-kl
job.type: search
search.type: ax
dataset.name: wnrr

# training settings (fixed)
train:
  max_epochs: 400
  auto_correct: True

# this is faster for smaller datasets, but does not work for some models (e.g.,
# TransE due to a pytorch issue) or for larger datasets. Change to spo in such
# cases (either here or in ax section of model config), results will not be
# affected.
negative_sampling.implementation: sp_po

# entity ranking settings
entity_ranking:
  query_types:
    sp_to_o: True
    po_to_s: True
    so_to_p: False

# KvsAll settings
1vsAll:
  query_types:
    sp_: True
    s_o: True
    _po: True

# validation/evaluation settings (fixed)
valid:
  every: 3
  metric: mean_reciprocal_rank_filtered_with_test
  filter_with_test: True
  early_stopping:
    patience: 0
    min_threshold.epochs: 50
    min_threshold.metric_value: 0.05

eval:
  batch_size: 256
  metrics_per.relation_type: True
  metrics_per.head_and_tail: True
  metrics_per.relation_prediction: False
  metrics_per.entity_prediction: True

# settings for reciprocal relations (if used)
import:
- complex
- reciprocal_relations_model
reciprocal_relations_model.base_model.type: complex
model: reciprocal_relations_model
# model: complex
# ax settings: hyperparameter serach space
ax_search:
  num_trials: 1
  num_sobol_trials: 1
  parameters:
    - name: train.batch_size
      type: fixed   
      value: 100
    - name: train.type
      type: fixed
      value: 1vsAll
    - name: train.optimizer
      type: fixed
      value: Adagrad
    - name: train.loss
      type: fixed
      value: kl
    - name: train.optimizer_args.lr
      type: fixed
      value: 0.1

    # embedding dimension
    - name: lookup_embedder.dim
      type: fixed 
      value: 2000
      is_ordered: True

    # embedding initialization
    - name: lookup_embedder.initial_scale
      type: fixed 
      value: 0.001
    - name: lookup_embedder.initialize
      type: fixed
      value: normal_
    - name: lookup_embedder.initialize_args.normal_.mean
      type: fixed
      value: 0.0
    - name: lookup_embedder.initialize_args.normal_.std
      type: fixed
      value: 1.0


    # embedding regularization
    - name: lookup_embedder.regularize
      type: fixed
      value: l3
    - name: lookup_embedder.AKBC_factors
      type: fixed
      value: True
    - name: lookup_embedder.regularize_args.weighted
      type: fixed
      value: True
    - name: complex.entity_embedder.regularize_weight
      type: fixed
      value: 0.6
    - name: complex.relation_embedder.regularize_weight
      type: fixed
      value: 0.3

    # embedding dropout
    - name: complex.entity_embedder.dropout
      type: fixed
      value: 0.0
    - name: complex.relation_embedder.dropout
      type: fixed
      value: 0.0

    # training-type specific hyperparameters
    # model-specific entries
    - name: 1vsAll.query_weight.s_o
      type: fixed
      value: 0.050
